### ISSUE TITLE
usb-device compatibility

### ISSUE THREAD

**Issue by dzervas** [jscarrott/nrf52840#9]
Hello, I'm trying to use the chip's USB device but can't figure how to implement the [UsbBus](https://docs.rs/usb-device/0.2.5/usb_device/bus/trait.UsbBus.html) trait - shouldn't that be implemented inside the pac? Can you give me any pointers on how to implement it?

**Comment by hannobraun** [comment]
Hi @dzervas. This should not be implemented in the PAC. The PAC is automatically generated from the vendor-provided SVD file and only forms the lowest layer of Rust support for the nRF52840. Higher-level code (like the USB implementation) should go into [nrf-hal](https://github.com/nrf-rs/nrf-hal).

It doesn't support USB yet, but there's a pull request for that here: https://github.com/nrf-rs/nrf-hal/pull/144
